import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeContextProvider from "@/lib/context/theme-context";
import ThemeSwitch from "@/lib/context/theme-switch";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Construction App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased p-4 bg-gray-50 text-gray-950 pt-4 sm:pt-12 dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90 mx-auto max-w-[1440px] pb-[10px] min-h-full relative`}
			>
				<ThemeContextProvider>
					{children}
					<ThemeSwitch />
				</ThemeContextProvider>
			</body>
		</html>
	);
}
