import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeContextProvider from "@/lib/context/theme-context";
import ThemeSwitch from "@/lib/context/theme-switch";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Construction App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<ThemeContextProvider>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiase bg-gray-50 text-gray-950 dark:bg-gray-900 dark:text-opacity-90 dark:text-gray-50 min-h-screen`}
				>
					<main className="p-4 pt-4 sm:pt-12 max-w-[1920px] mx-auto pb-[10px]">
						{children}
					</main>
					<ThemeSwitch />
				</body>
			</ThemeContextProvider>
		</html>
	);
}
